In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [6]:
import pandas as pd

In [15]:
iris = load_iris(as_frame=True)

In [16]:
type(iris)

sklearn.utils.Bunch

In [17]:
iris

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [18]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
iris['data']

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [20]:
iris_df = iris['data']

In [22]:
iris_df['target'] = iris['target']

In [25]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [24]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [72]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                random_state=101)

In [73]:
X_train,X_test,y_train,y_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
 104                6.5               3.0                5.8               2.2   
 89                 5.5               2.5                4.0               1.3   
 116                6.5               3.0                5.5               1.8   
 82                 5.8               2.7                3.9               1.2   
 112                6.8               3.0                5.5               2.1   
 ..                 ...               ...                ...               ...   
 63                 6.1               2.9                4.7               1.4   
 70                 5.9               3.2                4.8               1.8   
 81                 5.5               2.4                3.7               1.0   
 11                 4.8               3.4                1.6               0.2   
 95                 5.7               3.0                4.2               1.2   
 
      target  

In [74]:
type(X_train)

pandas.core.frame.DataFrame

In [75]:
dt_clf = DecisionTreeClassifier(random_state=101)

In [76]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=101)

In [77]:
pred = dt_clf.predict(X_test)

In [78]:
pred

array([0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0])

In [79]:
y_test

33     0
16     0
43     0
129    2
50     1
123    2
68     1
53     1
146    2
1      0
147    2
32     0
31     0
122    2
127    2
74     1
88     1
96     1
42     0
134    2
80     1
48     0
90     1
65     1
97     1
64     1
93     1
114    2
25     0
41     0
Name: target, dtype: int32

In [80]:
from sklearn.metrics import accuracy_score

In [81]:
accuracy_score(y_test,pred)

1.0

In [91]:
def test1(a,b):
    '''
    이함수는 결과값이 3개로 나갑니다.
    '''
    return a+b,a-b,a*b

In [ ]:
test1()

In [85]:
result = test1(1,2)

In [86]:
result

(3, -1, 2)

In [87]:
r1,r2,r3 = test1(3,4)

In [89]:
r1

7

In [90]:
r2

-1

# 과적합 참조
![과적합](과적합.png)

In [92]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [93]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [103]:
kfold = KFold(n_splits=5,shuffle=True)

In [104]:
cv_accuracy=[]

In [105]:
iris.data.shape

(150, 4)

In [106]:
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter +=1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 :{X_train.shape[0]}, 검증데이터 건수:{X_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9666666666666667
2번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9333333333333333
3번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9666666666666667
4번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9333333333333333
5번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9666666666666667
0.9533333333333334


In [113]:
kfold = KFold(n_splits=5,shuffle=True)
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # print(type(pd.Series(y_train)))
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 2    42
1    41
0    37
dtype: int64
검증용데이터 분포:
 0    13
1     9
2     8
dtype: int64
학습용데이터 분포:
 0    41
1    41
2    38
dtype: int64
검증용데이터 분포:
 2    12
0     9
1     9
dtype: int64
학습용데이터 분포:
 2    43
0    40
1    37
dtype: int64
검증용데이터 분포:
 1    13
0    10
2     7
dtype: int64
학습용데이터 분포:
 0    41
1    41
2    38
dtype: int64
검증용데이터 분포:
 2    12
0     9
1     9
dtype: int64
학습용데이터 분포:
 0    41
1    40
2    39
dtype: int64
검증용데이터 분포:
 2    11
1    10
0     9
dtype: int64


In [114]:
from sklearn.model_selection import StratifiedKFold

In [117]:
skfold = StratifiedKFold(n_splits=5,shuffle=True)
n_iter = 0
for train_index,test_index in skfold.split(iris.data,iris.target):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # print(type(pd.Series(y_train)))
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64


In [119]:
skfold = StratifiedKFold(n_splits=5,shuffle=True)
n_iter = 0
cv_accuracy=[]
for train_index,test_index in skfold.split(iris.data,iris.target):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter +=1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 :{X_train.shape[0]}, 검증데이터 건수:{X_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9333333333333333
2번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.8666666666666667
3번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9666666666666667
4번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:1.0
5번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9333333333333333
0.9400000000000001


In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [2]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [4]:
scores = cross_val_score(dt_clf,
                iris_data.data,
                iris_data.target,
                scoring='accuracy',
                cv=3)

In [5]:
import numpy as np
print('교차 검증별 정확도',scores)
print('평균 교차 검증 정확도',np.mean(scores))

교차 검증별 정확도 [0.98 0.94 0.98]
평균 교차 검증 정확도 0.9666666666666667


In [11]:
from sklearn.model_selection import GridSearchCV,train_test_split
import pandas as pd

In [7]:
grid_param = {'max_depth':[1,2,3],
              'min_samples_split':[2,3]}

In [9]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                 random_state=121)
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree,
                          param_grid=grid_param,
                          cv=3,
                          refit=True)
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [10]:
grid_dtree.cv_results_

{'mean_fit_time': array([0.        , 0.0003291 , 0.00066694, 0.        , 0.00033315,
        0.00033339]),
 'std_fit_time': array([0.        , 0.00046541, 0.0004716 , 0.        , 0.00047115,
        0.00047148]),
 'mean_score_time': array([0.0003558 , 0.        , 0.        , 0.00033951, 0.        ,
        0.        ]),
 'std_score_time': array([0.00050318, 0.        , 0.        , 0.00048014, 0.        ,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [13]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)

In [16]:
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [17]:
scores_df[['params',
           'mean_test_score',
           'rank_test_score',
           'split0_test_score',
           'split1_test_score',
           'split2_test_score' ]]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [19]:
grid_dtree.best_score_

0.975

In [20]:
grid_dtree.best_index_

4

In [23]:
pred = grid_dtree.best_estimator_.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
print('best estimator 정확도', accuracy_score(y_test,pred))

best estimator 정확도 0.9666666666666667


In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [30]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [32]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [33]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [35]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [39]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [40]:
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [43]:
labels.shape

(8,)

In [44]:
labels = labels.reshape(-1, 1)
labels.shape

(8, 1)

In [68]:
oh_encoder = OneHotEncoder(sparse=True)
oh_labels = oh_encoder.fit_transform(labels)

In [69]:
oh_encoder.categories_

[array([0, 1, 2, 3, 4, 5], dtype=int64)]

In [70]:
oh_encoder.sparse

True

In [71]:
oh_encoder

OneHotEncoder()

In [73]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [74]:
df = pd.DataFrame({'item':['TV',
                           '냉장고',
                           '전자레인지',
                           '컴퓨터',
                           '선풍기',
                           '선풍기',
                           '믹서',
                           '믹서']})

In [76]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [78]:
pd.get_dummies(df).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)